Suffix complex_alignof with U to hint the compiler that it is always unsigned
I have noticed a problem when compiling rumpkernel with the new
thread_get_name:

gnumachUser.c: In function 'thread_get_name':
gnumachUser.c:1791:37: error: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Werror=sign-compare]
 1791 |         if (mig_unlikely (msgh_size != 36 + ((OutP->nameType.msgt_number + 3) & ~3)))
      |                                     ^~
gnumachUser.c:25:47: note: in definition of macro 'mig_unlikely'
   25 | #define mig_unlikely(X) __builtin_expect (!! (X), 0)
      |                                               ^
cc1: all warnings being treated as errors

This ensures that the compiler won't cast ~3 to int since the code will
be written as:

 1791 |         if (mig_unlikely (msgh_size != 36 + ((OutP->nameType.msgt_number + 3) & ~3U)))
Message-ID: <hwbytulqiyx3ga3grvgpkgiekriqrogfv4lqasi74hqpeft7im@ipoz6pu44veo>